name: animated_gradient_button
description: A customizable animated gradient button for Flutter apps.
version: 0.1.0
homepage: https://github.com/kururu-abdo/animated_gradient_button.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter